### ISSUE TITLE
Can reset password because sendmail is not installed

### ISSUE THREAD

**Issue by chetanpatil1984** [linuxserver/docker-dokuwiki#10]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

If you are new to Docker or this application our issue tracker is **ONLY** used for reporting bugs or requesting features. Please use [our discord server](https://discord.gg/YWrKVTn) for general support.

Install DokuWiki wiki as documented.
Select closed installation with ACL enabled.
Enter the superuser name and password.
Try to login using superuser and password
[login fails]
Try to reset password for superuser.
[Fails because sendmail is not installed]

------------------------------

## Expected Behavior
Should be able to login using super user.
And should be able to reset password.

## Current Behavior
Unable to login using super user.
And unable to reset password.

## Steps to Reproduce

Install DokuWiki wiki as documented.
Select closed installation with ACL enabled.
Enter the superuser name and password.
Try to login using superuser and password
[login fails]
Try to reset password for superuser.
[Fails because sendmail is not installed]

## Environment
**OS:**      
**CPU architecture:** x86_64/arm32/arm64      
**How docker service was installed:**

**Comment by aptalca** [comment]
sendmail is in there:
```
root@953ddcb2547a:/# sendmail --help
BusyBox v1.31.1 () multi-call binary.

Usage: sendmail [-tv] [-f SENDER] [-amLOGIN 4<user_pass.txt | -auUSER -apPASS]
                [-w SECS] [-H 'PROG ARGS' | -S HOST] [RECIPIENT_EMAIL]...

Read email from stdin and send it

Standard options:
        -t              Read additional recipients from message body
        -f SENDER       For use in MAIL FROM:<sender>. Can be empty string
                        Default: -auUSER, or username of current UID
        -o OPTIONS      Various options. -oi implied, others are ignored
        -i              -oi synonym, implied and ignored

Busybox specific options:
        -v              Verbose
        -w SECS         Network timeout
        -H 'PROG ARGS'  Run connection helper. Examples:
                openssl s_client -quiet -tls1 -starttls smtp -connect smtp.gmail.com:25
                openssl s_client -quiet -tls1 -connect smtp.gmail.com:465
                        $SMTP_ANTISPAM_DELAY: seconds to wait after helper connect
        -S HOST[:PORT]  Server (default $SMTPHOST or 127.0.0.1)
        -amLOGIN        Log in using AUTH LOGIN
        -amPLAIN        or AUTH PLAIN
                        (-amCRAM-MD5 not supported)
        -auUSER         Username for AUTH
        -apPASS         Password for AUTH

If no -a options are given, authentication is not done.
If -amLOGIN is given but no -au/-ap, user/password is read from fd #4.
Other options are silently ignored; -oi is implied.
Use makemime to create emails with attachments.
```

**Comment by aptalca** [comment]
you can use one of the smtp plugins
