### ISSUE TITLE
Allowing configuring max upload size

### ISSUE THREAD

**Issue by Ryonez** [linuxserver/docker-dokuwiki#12]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

If you are new to Docker or this application our issue tracker is **ONLY** used for reporting bugs or requesting features. Please use [our discord server](https://discord.gg/YWrKVTn) for general support.

------------------------------

By default Dokuwiki has a 2M upload limit. I'd like to upload images to my wiki, but this prevents it.

Could you please set up a variable we can use that changes the limit please?
Documentation for the config location can be found here: https://www.dokuwiki.org/faq:uploadsize

**Comment by aptalca** [comment]
Well look into it. In the meantime, you can change the limits by editing the php config files in the config folder

**Comment by Ryonez** [comment]
Sorry, seems I didn't paste in the link.

Looking at their instructions though, and pocking at the files a little, I'm unsure where I'm meat to change this in the meantime. Would you be able to direct me to the file I need to adjust please?

**Comment by aptalca** [comment]
/config/php

**Comment by Ryonez** [comment]
![image](https://user-images.githubusercontent.com/16157130/82473519-cc2bc980-9b1d-11ea-85c4-71ae0f0e7acc.png)

That folder/file appears to be missing.

**Comment by Ryonez** [comment]
Omg, nevermind, I'm getting to tired >.<
I went the wrong way and stayed in the dokuwiki folder. Sorry about that.
