### ISSUE TITLE
Missing php extension

### ISSUE THREAD

**Issue by john-arvid** [linuxserver/docker-dokuwiki#13]
## Expected Behavior
Be able to use plugins.

## Current Behavior
Plugin not working because of missing php extension. Ref: [https://github.com/mizunashi-mana/dokuwiki-plugin-mdpage/issues/57](https://github.com/mizunashi-mana/dokuwiki-plugin-mdpage/issues/57)

## Steps to Reproduce

1. Start dokuwiki
2. Install mdpage plugin
3. Try to use the plugin

## Proposed solution
As mentioned in the issue the problem is solved by installing the php7-ctype. I will make a pull request for that.
Just wanted to put this issue out here so it is easier to keep track.

**Comment by tobbenb** [comment]
It's also possible to use our customizing option. Read https://blog.linuxserver.io/2019/09/14/customizing-our-containers/ for more info

**Comment by john-arvid** [comment]
Ok, so is that a better solution? 
Since there could be many problems like this for different plugins?
Or is the ctype extension so general that it should be included in the dockerfile?

**Comment by tobbenb** [comment]
As long as it's not an official plugin, the customisation option is better.

**Comment by mizunashi-mana** [comment]
DokuWiki use the ctype extension with polyfills.  So, if this image expect DokuWiki runs under normal performance, I recommend to include the ctype extension.

ref:

* An usage of ctype functions: https://github.com/splitbrain/dokuwiki/blob/release_stable_2018-04-22c/vendor/marcusschwarz/lesserphp/lessc.inc.php#L2870
* DokuWiki's polyfills: https://github.com/splitbrain/dokuwiki/blob/release_stable_2018-04-22c/inc/compatibility.php

**Comment by tobbenb** [comment]
If it's a part of the required dependencies, we'll add it.
