### ISSUE TITLE
Missing SQLite & PDO SQLite support (unable to use some plugins)

### ISSUE THREAD

**Issue by regystro** [linuxserver/docker-dokuwiki#25]
Hi.

To reproduce, after a fresh install go to Admin Panel > Extension Manager and install both [struct Plugin](https://www.dokuwiki.org/plugin:struct) and [sqlite Plugin](https://www.dokuwiki.org/plugin:sqlite). Then go to Admin Panel > Additional Plugins > Struct Schema Assignments and it'll throw these errors:
- SQLite & PDO SQLite support missing in this PHP install - plugin will not work
- The struct plugin requires the sqlite plugin. Please install and enable it.

So please, could you include php7-pdo_sqlite and php7-sqlite3 also?

Thank you!

**Comment by aptalca** [comment]
We can add them, but first, can you please exec in and install them inside the container via `apk add --no-cache` and confirm that it fixes your issue?
Thanks

**Comment by regystro** [comment]
I installed both `php7-pdo_sqlite` and `php7-sqlite3` and can confirm that the errors are gone and the aforementioned plugins are working properly.

Great, thanks :)
