### ISSUE TITLE
Pages sometimes don't load, or are missing information

### ISSUE THREAD

**Issue by DevinCampbell** [linuxserver/docker-dokuwiki#28]
## Expected Behavior
I click on a link in Trace or search for a page in the search bar, and it loads the page.

## Current Behavior
The page either loads with no information on it, doesn't load at all, or loads correctly.

## Steps to Reproduce
I'm not sure how to reproduce it because I'm not sure what is causing it.

## Environment
**OS: Ubuntu LTS 18.04
**CPU architecture:** x86_64
**How docker service was installed:

docker create \
  --name=dokuwiki \
  -e PUID=1000 \
  -e PGID=1000 \
  -e TZ=American/Chicago \
  -e APP_URL=/dokuwiki \
  --net=wan-accessible \
  -p 45000:80 \
  -p 45001:443 \
  -v /var/devin/dokuwiki:/config \
  --restart=always \
  linuxserver/dokuwiki

## Docker logs

If I run docker logs -f dokuwiki > log it endlessly scrolls with an nginx error. But if I look in the file log I get this:
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 01-envfile: executing...
[cont-init.d] 01-envfile: exited 0.
[cont-init.d] 10-adduser: executing...

-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/

Brought to you by linuxserver.io
-------------------------------------

To support LSIO projects visit:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------

User uid:    1000
User gid:    1000
-------------------------------------

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 20-config: executing...
[cont-init.d] 20-config: exited 0.
[cont-init.d] 30-keygen: executing...
using keys found in /config/keys
[cont-init.d] 30-keygen: exited 0.
[cont-init.d] 50-config: executing...
Existing install found install.php not available
[cont-init.d] Setting permissions this may take some time
[cont-init.d] 50-config: exited 0.
[cont-init.d] 99-custom-files: executing...
[custom-init] no custom files found exiting...
[cont-init.d] 99-custom-files: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.

#This is what I get when I try to watch the logs. Variations of this endlessly.
nginx: [emerg] bind() to 0.0.0.0:80 failed (98: Address in use)
nginx: [emerg] bind() to 0.0.0.0:443 failed (98: Address in use)
nginx: [emerg] bind() to 0.0.0.0:80 failed (98: Address in use)
nginx: [emerg] bind() to 0.0.0.0:443 failed (98: Address in use)
nginx: [emerg] bind() to 0.0.0.0:80 failed (98: Address in use)
nginx: [emerg] bind() to 0.0.0.0:443 failed (98: Address in use)
nginx: [emerg] bind() to 0.0.0.0:80 failed (98: Address in use)
nginx: [emerg] bind() to 0.0.0.0:443 failed (98: Address in use)
nginx: [emerg] bind() to 0.0.0.0:80 failed (98: Address in use)
nginx: [emerg] bind() to 0.0.0.0:443 failed (98: Address in use)

There are two other containers in the Docker network wan-accessible: linuxserver/swag and linuxserver/jellyfin. However, this issue occurs even if both of those containers are not running.

**Comment by coldshouldermedia** [comment]
I've had this behavior from a misbehaving plugin. To make sure it's it's not a plugin, disable them all from the plugin menu.  If that solves it, re-enable them one at a time to determine which plugin is causing the issue.

**Comment by DevinCampbell** [comment]
@coldshouldermedia I am unable to navigate to the plugin screen in Dokuwiki

**Comment by DevinCampbell** [comment]
> @coldshouldermedia I am unable to navigate to the plugin screen in Dokuwiki. Can I safely delete the directories in /dokuwiki/lib/plugins to test?

I tried using latest, version-2020-07-29, and 2020-07-29-ls53, and the nginx errors no longer come through my log, but the dokuwiki won't actually load when I navigate to 192.168.1.10:45000. I deleted every plugin except extension and config and it still will not load.

**Comment by DevinCampbell** [comment]
> > @coldshouldermedia I am unable to navigate to the plugin screen in Dokuwiki. Can I safely delete the directories in /dokuwiki/lib/plugins to test?
> 
> I tried using latest, version-2020-07-29, and 2020-07-29-ls53, and the nginx errors no longer come through my log, but the dokuwiki won't actually load when I navigate to 192.168.1.10:45000. I deleted every plugin except extension and config and it still will not load.

I have now tried using the 2020-07-29-ls42 and 2018-04-22c-ls41 versions. 2020-07-29-ls42 doesn't load the page, and 2018-04-22c-ls41 loads a page that says "DokuWiki Setup Error Something unforseen has happened: Maximum action transitions reached". At this point I don't know what the issue is or how to troubleshoot it.

**Comment by DevinCampbell** [comment]
I resolved this with the help of the LinuxServer.io Discord

**Comment by coldshouldermedia** [comment]
@DevinCampbell Please note what you did for folks in the future!
