### ISSUE TITLE
CLOUD plugin broken in this docker

### ISSUE THREAD

**Issue by joshuamallow** [linuxserver/docker-dokuwiki#4]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

If you are new to Docker or this application our issue tracker is **ONLY** used for reporting bugs or requesting features. Please use [our discord server](https://discord.gg/YWrKVTn) for general support.

------------------------------

## Expected Behavior
CLOUD plugin works in the latest version of DokuWiki, but for some reason this Docker it makes content on page not display.

## Current Behavior
When I add ~~TAGCLOUD~~ to any page, all of the content of that page displays as blank.

## Steps to Reproduce

1. Install TAG and CLOUD plugin
2. Add ~~TAGCLOUD~~ to page
3.
4.

## Environment
**OS:**      
**CPU architecture:** x86_64    
**How docker service was installed:**

**Comment by j0nnymoe** [comment]
Please can you provide more information? You haven't filled our all the questions in the issue template.

**Comment by j0nnymoe** [comment]
Closing as no response after 7 days.
