### ISSUE TITLE
new DokuWiki Version

### ISSUE THREAD

**Issue by Klar** [linuxserver/docker-dokuwiki#44]
there is a new DokuWiki Version: rc2022-06-26 "Igor" RC2

Would be nice to update / build this Docker to the new version.

**Comment by thespad** [comment]
It's still a release candidate and we don't have any development branches for this image, so it'll be a matter of waiting until it has a stable release.

**Comment by psych0d0g** [comment]
New release available: 2022-07-31 "Igor". [upgrade now!](http://download.dokuwiki.org/) [52.2] [(what's this?)](http://www.dokuwiki.org/update_check)

so its stable now ;)

**Comment by thespad** [comment]
Then it will get built the next time the CI checks for a new version.
