### ISSUE TITLE
latest docker image broken: expects wiki in /app/dokuwiki and not in /config

### ISSUE THREAD

**Issue by papamoose** [linuxserver/docker-dokuwiki#46]
Latest docker image breaks the wiki:

> The datadir ('pages') at /app/dokuwiki/data/pages is not found, isn't accessible or writable. You should check your config and permission settings. Or maybe you want to [run the installer](https://wiki.example.com/install.php)?

When the docker-compose example clearly shows:
```
    volumes:
      - /host/path/to/config:/config # Configuration files.
```

To get access to my wiki again using the latest version I did the following:

1. `docker-compose exec dokuwiki /bin/bash`
2. `cd /app`
3. `mv dokuwiki dokuwiki.bak`
4. `ln -s /config/dokuwiki /app/dokuwiki`
5. `mkdir cache locks tmp log`
6. `chown abc:users cache locks tmp log`

**Comment by thestraycat** [comment]
I have the same problem.

**Comment by papamoose** [comment]
@thestraycat What version are you using?

I expect this latest image broke a ton of people's wiki's.

**Comment by thestraycat** [comment]
@papamoose - I've rolled back to: lscr.io/linuxserver/dokuwiki:amd64-version-2020-07-29

**Comment by papamoose** [comment]
Possibly this code didn't run for some reason or there is a bug [root/etc/cont-init.d/50-config#49](https://github.com/linuxserver/docker-dokuwiki/blob/bbdb44adacd18706b9326e1b1f321cfa9c75b294/root/etc/cont-init.d/50-config#L49).

That code seems to be responsible for creating symlinks from /app to /config.

**Comment by geozeke** [comment]
Same here. Broken wiki. Thought I might be going crazy :-)

Thanks for the rollback info!

**Comment by kytay** [comment]
Thanks for posting the issue. I am facing the same issue.

**Comment by papamoose** [comment]
Pull request #45 looks related to this issue.

**Comment by Aerowinder** [comment]
Latest release (4 hours ago) resolved this issue for me.

**Comment by geozeke** [comment]
Great to hear! Digging into the commit that was part of [the pull request](https://github.com/linuxserver/docker-dokuwiki/pull/43/files#top) for that release, the issue may have been around line 47 of [this file](https://github.com/linuxserver/docker-dokuwiki/pull/43/files#diff-18bed53c5df14db4abf947a2d38ac6839c81e2b594cfb9e47dff912c9d4f06fb).

**Comment by couladin** [comment]
I had the same issue, with my ls133 container not surviving the ls134 upgrade. I opted for a full rebuild to ls134 just to see the difference and save time, though I wish I'd thought to check here again before I started (didn't notice ls135). :)

I used backed up copies of my local.php file and /config/dokuwiki/data/ directory, and added a volume bind for the latter to make backing up easier.

**Comment by papamoose** [comment]
Closing the loop on this. I updated to `version-2022-07-31` aka latest at time of writing. It all works now. I had to edit the nginx config to ensure was set `root /app/www/public;` but that was it.

**Comment by thestraycat** [comment]
:papamoose - Strange question, but does your 'Admin' button work on the mainpage?

**Comment by papamoose** [comment]
@thestraycat Yes it works.
