### ISSUE TITLE
Please update to the current version release_stable_2022-07-31a

### ISSUE THREAD

**Issue by update-freak** [linuxserver/docker-dokuwiki#49]
## Desired Behavior
Please update docker-dokuwiki to the current version 2022-07-31a which is released here: https://github.com/splitbrain/dokuwiki/releases/tag/release_stable_2022-07-31a

## Current Behavior
older version of dokuwiki

**Comment by thespad** [comment]
https://github.com/linuxserver/docker-dokuwiki/releases/tag/2022-07-31a-ls136
