### ISSUE TITLE
Support LDAP Authentication

### ISSUE THREAD

**Issue by lorenzschmid** [linuxserver/docker-dokuwiki#6]
Please excuse me for not using your proposed issue template as I would like to propose a feature request:

Dokuwiki comes pre-installed with a plugin that allows authentication via LDAP. In order for the LDAP plugin to work the `php7-ldap` package is required on a system level. I would thus propose to add it to the Dockerfiles, i.e.:

```Dockerfile
RUN \
  ...
  apk add --no-cache \
 	curl \
 	imagemagick \
 	php7-bz2 \
 	php7-gd \
 	php7-xml \
 	php7-zip \
 	php7-ldap  && \
  ...
```

**Comment by aptalca** [comment]
You can submit a PR
