### ISSUE TITLE
[BUG] Missing smileys

### ISSUE THREAD

**Issue by rardcode** [linuxserver/docker-dokuwiki#66]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When i insert :!: , icon doesn't appear

https://i.imgur.com/dczPBvy.png

and when i click in Smileys toolbar icon, list is empty

https://i.imgur.com/pJtxMj2.png

### Expected Behavior

image display all and correct

### Steps To Reproduce

new page, add :!: or choose smileys from toolbar

### Environment

```markdown
- OS:Linux Manjaro, dokuwiki 2023-04-04a
- How docker service was installed: Docker 24.0.6, build ed223bc820
```

### CPU architecture

x86-64

### Docker creation

```bash
version: "2.1"
services:
  dokuwiki:
    #image: linuxserver/dokuwiki:version-2022-07-31a
    image: linuxserver/dokuwiki:version-2023-04-04a
    container_name: dokuwiki
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Rome
    volumes:
      - ./data:/config
    #  - ./default.conf:/config/nginx/site-confs/default.conf
    #network_mode: host
    ports:
      - 8180:80
    #  #- 8143:443
    restart: unless-stopped
```

### Container logs

```bash
[migrations] started
[migrations] 01-nginx-site-confs-default: skipped
[migrations] 02-default-location: skipped
[migrations] done
───────────────────────────────────────

      ██╗     ███████╗██╗ ██████╗ 
      ██║     ██╔════╝██║██╔═══██╗
      ██║     ███████╗██║██║   ██║
      ██║     ╚════██║██║██║   ██║
      ███████╗███████║██║╚██████╔╝
      ╚══════╝╚══════╝╚═╝ ╚═════╝ 

   Brought to you by linuxserver.io
───────────────────────────────────────

To support LSIO projects visit:
https://www.linuxserver.io/donate/

───────────────────────────────────────
GID/UID
───────────────────────────────────────

User UID:    1000
User GID:    1000
───────────────────────────────────────

using keys found in /config/keys
chown: cannot access '/config/dokuwiki/lib/images/smileys/local': No such file or directory
**** Permissions could not be set. This is probably because your volume mounts are remote or read-only. ****
**** The app may not work properly and we will not provide support for it. ****
Existing install found, deleting install.php.
**** The following active confs have different version dates than the samples that are shipped. ****
**** This may be due to user customization or an update to the samples. ****
**** You should compare the following files to the samples in the same folder and update them. ****
**** Use the link at the top of the file to view the changelog. ****
┌────────────┬────────────┬────────────────────────────────────────────────────────────────────────┐
│  old date  │  new date  │ path                                                                   │
├────────────┼────────────┼────────────────────────────────────────────────────────────────────────┤
│ 2021-06-15 │ 2023-04-13 │ /config/nginx/nginx.conf                                               │
│ 2022-08-05 │ 2023-08-13 │ /config/nginx/ssl.conf                                                 │
│            │ 2023-04-13 │ /config/nginx/site-confs/default.conf                                  │
└────────────┴────────────┴────────────────────────────────────────────────────────────────────────┘
[custom-init] No custom files found, skipping...
[ls.io-init] done.
```

**Comment by rardcode** [comment]
Add data/log/nginx/error.log

`2023/10/25 16:41:03 [error] 383#383: *428 open() "/app/www/public/lib/images/smileys/icon_cool.gif" failed (2: No such file or directory), client: 10.99.5.1, server: _, request: "GET /lib/images/smileys/icon_cool.gif HTTP/1.1", host: "wiki.localdomain:8180", referrer: "http://wiki.localdomain:8180/doku.php?id=app:test&do=edit"
2023/10/25 16:41:03 [error] 383#383: *425 open() "/app/www/public/lib/images/smileys/icon_eek.gif" failed (2: No such file or directory), client: 10.99.5.1, server: _, request: "GET /lib/images/smileys/icon_eek.gif HTTP/1.1", host: "wiki.localdomain:8180", referrer: "http://wiki.localdomain:8180/doku.php?id=app:test&do=edit"
2023/10/25 16:41:03 [error] 383#383: *428 open() "/app/www/public/lib/images/smileys/icon_sad.gif" failed (2: No such file or directory), client: 10.99.5.1, server: _, request: "GET /lib/images/smileys/icon_sad.gif HTTP/1.1", host: "wiki.localdomain:8180", referrer: "http://wiki.localdomain:8180/doku.php?id=app:test&do=edit"
2023/10/25 16:41:03 [error] 383#383: *425 open() "/app/www/public/lib/images/smileys/icon_smile.gif" failed (2: No such file or directory), client: 10.99.5.1, server: _, request: "GET /lib/images/smileys/icon_smile.gif HTTP/1.1", host: "wiki.localdomain:8180", referrer: "http://wiki.localdomain:8180/doku.php?id=app:test&do=edit"
2023/10/25 16:41:03 [error] 383#383: *430 open() "/app/www/public/lib/images/smileys/icon_smile2.gif" failed (2: No such file or directory), client: 10.99.5.1, server: _, request: "GET /lib/images/smileys/icon_smile2.gif HTTP/1.1", host: "wiki.localdomain:8180", referrer: "http://wiki.localdomain:8180/doku.php?id=app:test&do=edit"
2023/10/25 16:41:03 [error] 384#384: *431 open() "/app/www/public/lib/images/smileys/icon_doubt.gif" failed (2: No such file or directory), client: 10.99.5.1, server: _, request: "GET /lib/images/smileys/icon_doubt.gif HTTP/1.1", host: "wiki.localdomain:8180", referrer: "http://wiki.localdomain:8180/doku.php?id=app:test&do=edit"
2023/10/25 16:41:03 [error] 384#384: *432 open() "/app/www/public/lib/images/smileys/icon_doubt2.gif" failed (2: No such file or directory), client: 10.99.5.1, server: _, request: "GET /lib/images/smileys/icon_doubt2.gif HTTP/1.1", host: "wiki.localdomain:8180", referrer: "http://wiki.localdomain:8180/doku.php?id=app:test&do=edit"
2023/10/25 16:41:03 [error] 384#384: *433 open() "/app/www/public/lib/images/smileys/icon_confused.gif" failed (2: No such file or directory), client: 10.99.5.1, server: _, request: "GET /lib/images/smileys/icon_confused.gif HTTP/1.1", host: "wiki.localdomain:8180", referrer: "http://wiki.localdomain:8180/doku.php?id=app:test&do=edit"
2023/10/25 16:41:03 [error] 384#384: *431 open() "/app/www/public/lib/images/smileys/icon_biggrin.gif" failed (2: No such file or directory), client: 10.99.5.1, server: _, request: "GET /lib/images/smileys/icon_biggrin.gif HTTP/1.1", host: "wiki.localdomain:8180", referrer: "http://wiki.localdomain:8180/doku.php?id=app:test&do=edit"
2023/10/25 16:41:03 [error] 383#383: *430 open() "/app/www/public/lib/images/smileys/icon_razz.gif" failed (2: No such file or directory), client: 10.99.5.1, server: _, request: "GET /lib/images/smileys/icon_razz.gif HTTP/1.1", host: "wiki.localdomain:8180", referrer: "http://wiki.localdomain:8180/doku.php?id=app:test&do=edit"
2023/10/25 16:41:03 [error] 384#384: *432 open() "/app/www/public/lib/images/smileys/icon_surprised.gif" failed (2: No such file or directory), client: 10.99.5.1, server: _, request: "GET /lib/images/smileys/icon_surprised.gif HTTP/1.1", host: "wiki.localdomain:8180", referrer: "http://wiki.localdomain:8180/doku.php?id=app:test&do=edit"
2023/10/25 16:41:03 [error] 383#383: *425 open() "/app/www/public/lib/images/smileys/icon_silenced.gif" failed (2: No such file or directory), client: 10.99.5.1, server: _, request: "GET /lib/images/smileys/icon_silenced.gif HTTP/1.1", host: "wiki.localdomain:8180", referrer: "http://wiki.localdomain:8180/doku.php?id=app:test&do=edit"
2023/10/25 16:41:03 [error] 383#383: *428 open() "/app/www/public/lib/images/smileys/icon_neutral.gif" failed (2: No such file or directory), client: 10.99.5.1, server: _, request: "GET /lib/images/smileys/icon_neutral.gif HTTP/1.1", host: "wiki.localdomain:8180", referrer: "http://wiki.localdomain:8180/doku.php?id=app:test&do=edit"
2023/10/25 16:41:03 [error] 383#383: *430 open() "/app/www/public/lib/images/smileys/icon_wink.gif" failed (2: No such file or directory), client: 10.99.5.1, server: _, request: "GET /lib/images/smileys/icon_wink.gif HTTP/1.1", host: "wiki.localdomain:8180", referrer: "http://wiki.localdomain:8180/doku.php?id=app:test&do=edit"
2023/10/25 16:41:03 [error] 384#384: *432 open() "/app/www/public/lib/images/smileys/facepalm.gif" failed (2: No such file or directory), client: 10.99.5.1, server: _, request: "GET /lib/images/smileys/facepalm.gif HTTP/1.1", host: "wiki.localdomain:8180", referrer: "http://wiki.localdomain:8180/doku.php?id=app:test&do=edit"
2023/10/25 16:41:03 [error] 384#384: *433 open() "/app/www/public/lib/images/smileys/icon_fun.gif" failed (2: No such file or directory), client: 10.99.5.1, server: _, request: "GET /lib/images/smileys/icon_fun.gif HTTP/1.1", host: "wiki.localdomain:8180", referrer: "http://wiki.localdomain:8180/doku.php?id=app:test&do=edit"
2023/10/25 16:41:03 [error] 383#383: *425 open() "/app/www/public/lib/images/smileys/icon_question.gif" failed (2: No such file or directory), client: 10.99.5.1, server: _, request: "GET /lib/images/smileys/icon_question.gif HTTP/1.1", host: "wiki.localdomain:8180", referrer: "http://wiki.localdomain:8180/doku.php?id=app:test&do=edit"
2023/10/25 16:41:03 [error] 383#383: *430 open() "/app/www/public/lib/images/smileys/icon_exclaim.gif" failed (2: No such file or directory), client: 10.99.5.1, server: _, request: "GET /lib/images/smileys/icon_exclaim.gif HTTP/1.1", host: "wiki.localdomain:8180", referrer: "http://wiki.localdomain:8180/doku.php?id=app:test&do=edit"
2023/10/25 16:41:03 [error] 383#383: *428 open() "/app/www/public/lib/images/smileys/icon_lol.gif" failed (2: No such file or directory), client: 10.99.5.1, server: _, request: "GET /lib/images/smileys/icon_lol.gif HTTP/1.1", host: "wiki.localdomain:8180", referrer: "http://wiki.localdomain:8180/doku.php?id=app:test&do=edit"
2023/10/25 16:41:03 [error] 384#384: *432 open() "/app/www/public/lib/images/smileys/fixme.gif" failed (2: No such file or directory), client: 10.99.5.1, server: _, request: "GET /lib/images/smileys/fixme.gif HTTP/1.1", host: "wiki.localdomain:8180", referrer: "http://wiki.localdomain:8180/doku.php?id=app:test&do=edit"
2023/10/25 16:41:03 [error] 383#383: *430 open() "/app/www/public/lib/images/smileys/delete.gif" failed (2: No such file or directory), client: 10.99.5.1, server: _, request: "GET /lib/images/smileys/delete.gif HTTP/1.1", host: "wiki.localdomain:8180", referrer: "http://wiki.localdomain:8180/doku.php?id=app:test&do=edit"
`

**Comment by rardcode** [comment]
whith this command launced inside docker i've solved:
`cp -a /config/dokuwiki/lib/images/smileys/* /app/www/public/lib/images/smileys/
`
but if i will restart docker?!?

**Comment by thespad** [comment]
We symlink `lib/images/smileys/local` but we don't touch `lib/images/smileys` so the files shouldn't be in /config to copy in the first place.

**Comment by rardcode** [comment]
as you can see from the error log,
`open() "/app/www/public/lib/images/smileys/fixme.gif" failed (2: No such file or directory)`

webserver search image in `/app/www/public/lib/images/smileys/fixme.gif` but there are in `/config/dokuwiki/lib/images/smileys/`

right?

**Comment by rardcode** [comment]
i've removed and recreated container and it'ok...thanks for all
Maybe I had deleted the smilies by mistake?
bha... now it'all ok

**Comment by rardcode** [comment]
for info problem was name of smileys in my config file `data/dokuwiki/conf/smileys.conf`

```
# Smileys configured here will be replaced by the
# configured images in the smiley directory

8-)         icon_cool.gif
8-O         icon_eek.gif
8-o         icon_eek.gif
:-(         icon_sad.gif
:-)         icon_smile.gif
=)          icon_smile2.gif
:-/         icon_doubt.gif
:-\         icon_doubt2.gif
:-?         icon_confused.gif
:-D         icon_biggrin.gif
:-P         icon_razz.gif
:-o         icon_surprised.gif
:-O         icon_surprised.gif
:-x         icon_silenced.gif
:-X         icon_silenced.gif
:-|         icon_neutral.gif
;-)         icon_wink.gif
m(          facepalm.gif
^_^         icon_fun.gif
:?:         icon_question.gif
:!:         icon_exclaim.gif
LOL         icon_lol.gif
FIXME       fixme.gif
DELETEME    delete.gif
```

correct name are:
```
# Smileys configured here will be replaced by the
# configured images in the smiley directory

8-)         cool.svg
8-O         eek.svg
:-(         sad.svg
:-)         smile.svg
=)          smile2.svg
:-/         doubt.svg
:-\         doubt2.svg
:-?         confused.svg
:-D         biggrin.svg
:-P         razz.svg
:-O         surprised.svg
:-X         silenced.svg
:-|         neutral.svg
;-)         wink.svg
m(          facepalm.svg
^_^         fun.svg
:?:         question.svg
:!:         exclaim.svg
LOL         lol.svg
FIXME       fixme.svg
DELETEME    deleteme.svg
```

some version upgrade has change smileys file?
