### ISSUE TITLE
[FEAT] Addition of php8.2-intl

### ISSUE THREAD

**Issue by spacecake** [linuxserver/docker-dokuwiki#67]
### Is this a new feature request?

- [X] I have searched the existing issues

### Wanted change

Add php8.2-intl to the docker base image.

### Reason for change

Hello

The Dokuwiki plugin [Combo](https://www.dokuwiki.org/plugin:combo) gives errors when installed.

The critical error received:
`
Error: Class "IntlDateFormatter" not found

An unforeseen error has occured. This is most likely a bug somewhere. It might be a problem in the combo plugin.

More info has been written to the DokuWiki error log.
`

In my brief research I found several solution pointing to this change: [stackoverflow](https://stackoverflow.com/questions/6242378/fatal-error-class-intldateformatter-not-found), 
In the docker image a "find / -name php* 2>/dev/null" did not give me answers and did not find any in /usr/lib/php82/modules

Did I missed something?

### Proposed code change

Kindly, include php8.2-intl extension in the image.

**Comment by Roxedus** [comment]
This looks like a 3rd-party plugin for docuwiki, and I don't see why this extension is needed in the image. You can however use the [Package Install](https://github.com/linuxserver/docker-mods/tree/universal-package-install#package-install---universal-docker-mod) mod to install it in your instance.

**Comment by spacecake** [comment]
Solution:
>    environment:
>       - DOCKER_MODS=linuxserver/mods:universal-package-install
>       - INSTALL_PACKAGES=php82-intl

Thank you Roxedus!
