### ISSUE TITLE
[BUG] Dokuwiki plugins can't access DokuWiki language files.

### ISSUE THREAD

**Issue by lopar** [linuxserver/docker-dokuwiki#73]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Current chmods in container are:

```
/# ls -l /config/dokuwiki/                                     
total 8                                                                          
drwxr-xr-x 1 abc  abc  796 Apr  5 17:39 conf                                     
drwx------ 1 abc  abc  542 Feb 29 13:39 data                                     
lrwxrwxrwx 1 root root  19 Apr  2 13:17 inc -> /app/www/public/inc               
drwx------ 1 abc  abc   84 Feb 29 13:39 lib                                      
lrwxrwxrwx 1 root root  22 Apr  2 13:17 vendor -> /app/www/public/vendor         
```

No one can modify `inc/lang/`. Only `conf/`, `data/` and `lib/` are accessible.

### Expected Behavior

Plugins in `dokiwiki/lib/plugins/PluginName/file.php` should have rw access to `dokuwiki/inc/lang/`. 

Looks like, somehow core constant  `define('DOKU_INC', realpath(__DIR__ . '/../') . '/')` in `dokuwiki/bin/plugin.php` generates wrong path when using in `DOKU_INC . "inc/lang/"`.

That is permission problem inside container with (looks like) modified DokuWiki base file structure, I don't know how to correctly explain this. But the container should be rebuilded somehow under the circumstances.

### Steps To Reproduce

Just use any DokuWiki plugin that modifies core languages. They won't do anything and won't show any errors.

### Environment

```markdown
- OS: Synology DSM 7.2
- How docker service was installed: Vendor's package.
```

### CPU architecture

x86-64

### Docker creation

```bash
services:
  dokuwiki:
    image: lscr.io/linuxserver/dokuwiki:latest
    container_name: dokuwiki
    environment:
      - PUID=XXX
      - PGID=XXX
      - TZ=Europe/Kyiv
    volumes:
      - ./dokuwiki:/config/dokuwiki
    ports:
      - 8089:80
    restart: unless-stopped
```
```


### Container logs

```bash
No errors in stdout.
```

**Comment by thespad** [comment]
So I've been looking into this and there's a core problem that I can't really solve.

I can sort the permissions, that's not a problem, but the lang files are still going to be in the container filesystem which won't persist updates. I can't move the files out of the container filesystem into persistent storage because then they won't get updated when dokuwiki updates them.
